// Autogenerated AST node
package org.python.antlr.ast;
import org.antlr.runtime.CommonToken;
import org.antlr.runtime.Token;
import org.python.antlr.AST;
import org.python.antlr.PythonTree;
import org.python.antlr.adapter.AstAdapters;
import org.python.antlr.base.excepthandler;
import org.python.antlr.base.expr;
import org.python.antlr.base.mod;
import org.python.antlr.base.slice;
import org.python.antlr.base.stmt;
import org.python.core.ArgParser;
import org.python.core.AstList;
import org.python.core.Py;
import org.python.core.PyObject;
import org.python.core.PyString;
import org.python.core.PyType;
import org.python.expose.ExposedGet;
import org.python.expose.ExposedMethod;
import org.python.expose.ExposedNew;
import org.python.expose.ExposedSet;
import org.python.expose.ExposedType;
import java.io.DataOutputStream;
import java.io.IOException;

//import java.sql.*;
//import java.sql.DriverManager;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.LinkedList;
import java.util.Map;
import java.util.Queue;
import java.util.Random;


import com.hp.hpl.jena.query.Query;
import com.hp.hpl.jena.query.QueryExecution;
import com.hp.hpl.jena.query.QueryFactory;
import com.hp.hpl.jena.query.*;
import com.hp.hpl.jena.tdb.*;
import com.hp.hpl.jena.rdf.model.*;

@ExposedType(name = "_ast.SQLInsert", base = AST.class)
public class SQLInsert extends stmt {
public static final PyType TYPE = PyType.fromClass(SQLInsert.class);
    private expr dest;
    public expr getInternalDest() {
        return dest;
    }
    @ExposedGet(name = "dest")
    public PyObject getDest() {
        return dest;
    }
    @ExposedSet(name = "dest")
    public void setDest(PyObject dest) {
        this.dest = AstAdapters.py2expr(dest);
    }

    private java.util.List<expr> values;
    public java.util.List<expr> getInternalValues() {
        return values;
    }
    @ExposedGet(name = "values")
    public PyObject getValues() {
        return new AstList(values, AstAdapters.exprAdapter);
    }
    @ExposedSet(name = "values")
    public void setValues(PyObject values) {
        this.values = AstAdapters.py2exprList(values);
    }

    private Boolean nl;
    public Boolean getInternalNl() {
        return nl;
    }
    @ExposedGet(name = "nl")
    public PyObject getNl() {
        if (nl) return Py.True;
        return Py.False;
    }
    @ExposedSet(name = "nl")
    public void setNl(PyObject nl) {
        this.nl = AstAdapters.py2bool(nl);
    }


    private final static PyString[] fields =
    new PyString[] {new PyString("dest"), new PyString("values"), new PyString("nl")};
    @ExposedGet(name = "_fields")
    public PyString[] get_fields() { return fields; }

    private final static PyString[] attributes =
    new PyString[] {new PyString("lineno"), new PyString("col_offset")};
    @ExposedGet(name = "_attributes")
    public PyString[] get_attributes() { return attributes; }

    public SQLInsert(PyType subType) {
        super(subType);
    }
    public SQLInsert() {
        this(TYPE);
    }
    @ExposedNew
    @ExposedMethod
    public void SQLInsert___init__(PyObject[] args, String[] keywords) {
        ArgParser ap = new ArgParser("SQLInsert", args, keywords, new String[]
            {"dest", "values", "nl", "lineno", "col_offset"}, 3, true);
        setDest(ap.getPyObject(0, Py.None));
        setValues(ap.getPyObject(1, Py.None));
        setNl(ap.getPyObject(2, Py.None));
        int lin = ap.getInt(3, -1);
        if (lin != -1) {
            setLineno(lin);
        }

        int col = ap.getInt(4, -1);
        if (col != -1) {
            setLineno(col);
        }

    }

    private Queue<String> qtbls = new LinkedList<String>();
    private Queue<java.util.List> qattrs = new LinkedList<java.util.List>();
    
    public static Map<String,SQLInsert>  SQLInserts = new HashMap<String, SQLInsert>();
    public static Integer entnum = new Integer(214);
    
    public SQLInsert(int dummy, Token token, String table, java.util.List<String> attrs, java.util.List<expr> values) {
        super(token);
        SQLInserts.put(this.toString(), this);
        qtbls.add(table);
        qattrs.add(attrs);
        this.values = values;
        if (values == null) {
            this.values = new ArrayList<expr>();
        }
        for (PythonTree t : this.values) {
            addChild(t);
        }
        // this.nl = nl;
    }    
    
    public static void sqlGetInsertProcessor(java.util.List<PyObject> insert, String node_name) {
        SQLInserts.get(node_name).sqlProcessInsert(insert);
        // SQLInserts.remove(node_name);
    }

    public void sqlProcessInsert(java.util.List<PyObject> insert) {

        // Directory of store
        // String directory = "C:\\GitJython\\TDB Data";
        String directory = "tdb";

        // Make or restore TDB-backed Jena model in the named directory.
        Model model = TDBFactory.createModel(directory);
        model.close();

        // Add facts to model
        String empUri = "http://employee/";
        String propertyUri = "http://emp/property/";
        String key = entnum.toString(); entnum++;
        java.util.List a = qattrs.remove();
        qattrs.add(a);
        for (int i = 0; i < a.size(); i++) {
            Resource s1 = model.createResource(empUri + key);
            Property p1 = model.createProperty(propertyUri + a.get(i).toString());
            s1.addProperty(p1, insert.get(i).toString());
        }   
        // Synchronize
        TDB.sync(model);
        // Close
        model.close();
    }
    
    public String toStringTree() {
        StringBuffer sb = new StringBuffer("SQLInsert(");
        sb.append("dest=");
        sb.append(dumpThis(dest));
        sb.append(",");
        sb.append("values=");
        sb.append(dumpThis(values));
        sb.append(",");
        sb.append("nl=");
        sb.append(dumpThis(nl));
        sb.append(",");
        sb.append(")");
        return sb.toString();
    }

    public <R> R accept(VisitorIF<R> visitor) throws Exception {
        return visitor.visitSQLInsert(this);
    }

    public void traverse(VisitorIF<?> visitor) throws Exception {
        if (dest != null)
            dest.accept(visitor);
        if (values != null) {
            for (PythonTree t : values) {
                if (t != null)
                    t.accept(visitor);
            }
        }
    }

    private int lineno = -1;
    @ExposedGet(name = "lineno")
    public int getLineno() {
        if (lineno != -1) {
            return lineno;
        }
        return getLine();
    }

    @ExposedSet(name = "lineno")
    public void setLineno(int num) {
        lineno = num;
    }

    private int col_offset = -1;
    @ExposedGet(name = "col_offset")
    public int getCol_offset() {
        if (col_offset != -1) {
            return col_offset;
        }
        return getCharPositionInLine();
    }

    @ExposedSet(name = "col_offset")
    public void setCol_offset(int num) {
        col_offset = num;
    }

}
